# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 09:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 19, 15, 8, 49, 988102)),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
