# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170819_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 19, 15, 10, 17, 311665)),
        ),
    ]
