# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 09:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20170819_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 19, 9, 42, 8, 995937, tzinfo=utc)),
        ),
    ]
