# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 11:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20170819_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='daysBeforeShipping',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 19, 16, 59, 15, 163706)),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=2),
        ),
    ]
