# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 07:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20170820_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 13, 14, 48, 24180)),
        ),
    ]
