# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20170920_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_in_rupees',
            field=models.IntegerField(default=0),
        ),
    ]
