# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_discount_in_rupees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_in_rupees',
            new_name='discount_in_percent',
        ),
    ]
