# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20171020_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='og_price',
            field=models.IntegerField(default=0),
        ),
    ]
