# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
