# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20171021_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
