# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-31 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_product_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='notes',
            new_name='shop_name',
        ),
    ]
