# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170826_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=600),
        ),
    ]
