# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-30 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20171101_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cc',
        ),
        migrations.AddField(
            model_name='profile',
            name='alt_phone_number',
            field=models.CharField(default=1234567890, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Jalandhar', max_length=600),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
    ]
