# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-30 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180330_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gst',
            field=models.CharField(default=123456, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='pan',
            field=models.CharField(default=123456, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='shopname',
            field=models.CharField(default='Aggarwal Bakery', max_length=100),
            preserve_default=False,
        ),
    ]
