# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-30 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180330_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accountholder',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='prodtype',
            field=models.CharField(default='bakery', max_length=200),
            preserve_default=False,
        ),
    ]
