# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-30 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180331_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='IFSC_code',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='account_number',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
