# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20170901_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
